const CATS=['Basic Attacks','Jumping Attacks','Hop Attacks','Getup Attacks','Flawless Block Attacks','Throws','Roll Escapes','Air Escape','Combo Attacks'];
const DIR={F:'→',B:'←',U:'↑',D:'↓'};
const BUTTONS=new Set(['Y','X','B','A','L','R','ZL','ZR','LT','RT']);
let DB=null, fighter=null, selected=null, facing='right', timer=null, stepIndex=0, altIndex=0;
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const buttonLabel=k=>k==='LT'?'ZL':k==='RT'?'ZR':k;
function dirLabel(d){let x=DIR[d]||d; if(facing==='left'&&(d==='F'||d==='B')) x=d==='F'?'←':'→'; return x}
function stepText(step){return [...(step.directions||[]).map(dirLabel),...(step.buttons||[]).map(buttonLabel)].join(' + ')}
function flatSteps(move){const alts=move.alternatives||[]; return alts.length?alts[altIndex%alts.length]:[]}
function allFighters(){return DB.characters.filter(c=>c.name!=='Unannounced')}
function moveCount(c){return c.moves.length}
function renderHome(){fighter=null;selected=null;$('#back').hidden=true;$('#title').textContent='Choose Fighter';$('#screen').innerHTML=`<div class="homeTop"><div><div class="hint">Offline database · ${moveCountTotal()} moves · ${allFighters().length} fighters</div></div><input class="search" id="q" placeholder="Search fighter or move…"></div><div class="grid" id="fighters">${allFighters().map(c=>`<button class="fighter" data-f="${esc(c.name)}"><span class="fighterName">${esc(c.name)}</span><span>${moveCount(c)} moves</span></button>`).join('')}</div><details class="source"><summary>Database</summary><p>Embedded locally from the supplied Nintendo Switch source. No Internet is required to consult the moves.</p><p class="hint">Source update: ${esc(DB.source_updated)} · ${moveCountTotal()} entries.</p></details>`;document.querySelectorAll('.fighter').forEach(b=>b.onclick=()=>showFighter(b.dataset.f));$('#q').oninput=e=>filterCards(e.target.value)}
function filterCards(q){q=q.toLowerCase().trim();document.querySelectorAll('.fighter').forEach(b=>{b.hidden=!!q&&!b.innerText.toLowerCase().includes(q)})}
function showFighter(name){fighter=DB.characters.find(c=>c.name===name);selected=null;stepIndex=0;altIndex=0;$('#back').hidden=false;$('#title').textContent=name;renderFighter()}
function renderFighter(){const cats=CATS.filter(cat=>fighter.moves.some(m=>m.category===cat));$('#screen').innerHTML=`<div class="layout"><aside class="moves"><div class="toolbar"><input class="search" id="mq" placeholder="Search move…"></div>${cats.map(cat=>`<div class="cat">${esc(cat)}</div>${fighter.moves.filter(m=>m.category===cat).map(m=>`<button class="move" data-id="${esc(m.name)}" data-cat="${esc(cat)}"><span><b>${esc(m.name)}</b>${m.starred?'<i>variation</i>':''}</span><small>${esc(shortInput(m))}</small></button>`).join('')}</aside><section class="practice"><div class="practiceHead"><div><div class="eyebrow">PRACTICE MODE</div><h2 id="mname">Select a move</h2><div id="meta" class="hint"></div></div><label class="toggle">Facing <select id="face"><option value="right">→ RIGHT</option><option value="left">← LEFT</option></select></label></div><div id="seq" class="seq"><span class="hint">Select a move from the list</span></div><div id="alt" class="alt"></div><div class="controller"><div class="joy leftJoy"><div class="stick joyStick"></div><div class="dpad"><button data-k="U">↑</button><button data-k="D">↓</button><button data-k="B">←</button><button data-k="F">→</button></div><div class="joyLabel">−</div></div><div class="bridge"></div><div class="joy rightJoy"><div class="faceButtons"><button data-k="Y">Y</button><button data-k="X">X</button><button data-k="A">A</button><button data-k="B">B</button></div><div class="stick joyStick"></div><div class="joyLabel">+</div></div><button class="shoulder zl" data-k="ZL">ZL</button><button class="shoulder zr" data-k="ZR">ZR</button></div><div class="controls"><button class="small" id="prev">← Previous</button><button class="primary" id="play">▶ Practice / Loop</button><button class="small" id="next">Next →</button></div><div class="hint">Yellow = press now. A group joined by <b>+</b> is simultaneous. Steps separated by arrows are sequential. Slash = alternative input.</div></section></div>`;document.querySelectorAll('.move').forEach(b=>b.onclick=()=>selectMove(b.dataset.id,b.dataset.cat));$('#face').value=facing;$('#face').onchange=e=>{facing=e.target.value;renderSteps()};$('#play').onclick=togglePlay;$('#prev').onclick=()=>advance(-1);$('#next').onclick=()=>advance(1);$('#mq').oninput=e=>{let q=e.target.value.toLowerCase().trim();document.querySelectorAll('.move').forEach(b=>b.hidden=!!q&&!b.innerText.toLowerCase().includes(q))}}
function shortInput(m){return (m.alternatives||[]).map(a=>a.map(stepText).join('  ')).join(' / ')}
function selectMove(name,cat){stopPlay();selected=fighter.moves.find(m=>m.name===name&&m.category===cat);stepIndex=0;altIndex=0;document.querySelectorAll('.move').forEach(b=>b.classList.toggle('active',b.dataset.id===name&&b.dataset.cat===cat));$('#mname').textContent=selected.name;$('#meta').textContent=[selected.category,selected.damage?`${selected.damage} damage`:null,selected.note].filter(Boolean).join(' · ');renderSteps()}
function renderSteps(){if(!selected)return;const steps=flatSteps(selected);if(!steps.length)return;stepIndex=((stepIndex%steps.length)+steps.length)%steps.length;$('#seq').innerHTML=steps.map((s,i)=>`<span class="step ${i===stepIndex?'on':''}">${esc(stepText(s))}</span>${i<steps.length-1?'<span class="arrow">→</span>':''}`).join('');$('#alt').innerHTML=(selected.alternatives||[]).length>1?`Alternative ${altIndex+1} / ${selected.alternatives.length} <button class="small" id="altBtn">Switch</button>`:'';if($('#altBtn'))$('#altBtn').onclick=()=>{altIndex=(altIndex+1)%selected.alternatives.length;stepIndex=0;renderSteps()};document.querySelectorAll('[data-k]').forEach(b=>b.classList.remove('activeBtn'));const current=steps[stepIndex];(current.directions||[]).forEach(d=>highlightDir(d));(current.buttons||[]).forEach(k=>highlightButton(buttonLabel(k)))}
function highlightDir(d){document.querySelectorAll(`[data-k="${d}"]`).forEach(b=>b.classList.add('activeBtn'))}
function highlightButton(k){document.querySelectorAll(`[data-k="${k}"]`).forEach(b=>b.classList.add('activeBtn'))}
function advance(n){if(!selected)return;stepIndex+=n;renderSteps()}
function togglePlay(){if(timer){stopPlay();return}timer=setInterval(()=>{stepIndex++;const steps=flatSteps(selected||{});if(steps.length&&stepIndex>=steps.length)stepIndex=0;renderSteps()},650);$('#play').textContent='⏸ Stop'}
function stopPlay(){if(timer){clearInterval(timer);timer=null}const p=$('#play');if(p)p.textContent='▶ Practice / Loop'}
function moveCountTotal(){return DB.characters.reduce((n,c)=>n+c.moves.length,0)}
async function load(){const raw=atob(window.MK11_DB_GZIP_B64);const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));const text=await new Response(stream).text();DB=JSON.parse(text);renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')}
$('#back').onclick=()=>{stopPlay();renderHome()};load().catch(e=>{$('#screen').innerHTML='<div class="empty">Could not load the embedded database.</div>';console.error(e)});
